"""initial_schema

Revision ID: 8a594c7aa925
Revises: 
Create Date: 2026-05-06 03:12:43.631661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a594c7aa925'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_alumnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(), nullable=False),
    sa.Column('apellido_paterno', sa.String(), nullable=False),
    sa.Column('apellido_materno', sa.String(), nullable=False),
    sa.Column('nombres', sa.String(), nullable=False),
    sa.Column('carrera', sa.String(), nullable=False),
    sa.Column('cuatrimestre', sa.Integer(), nullable=False),
    sa.Column('grupo', sa.String(), nullable=False),
    sa.Column('periodo', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula', 'periodo', name='uq_alumno_matricula_periodo')
    )
    with op.batch_alter_table('catalogo_alumnos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalogo_alumnos_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalogo_alumnos_matricula'), ['matricula'], unique=False)

    op.create_table('catalogo_materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('carrera', sa.String(), nullable=True),
    sa.Column('cuatrimestre_oficial', sa.Integer(), nullable=True),
    sa.Column('periodo', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalogo_materias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalogo_materias_id'), ['id'], unique=False)

    op.create_table('laboratorios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('ubicacion', sa.String(), nullable=True),
    sa.Column('capacidad', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('laboratorios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_laboratorios_id'), ['id'], unique=False)

    op.create_table('activos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('laboratorio_id', sa.Integer(), nullable=False),
    sa.Column('codigo_inventario', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('marca', sa.String(), nullable=True),
    sa.Column('modelo', sa.String(), nullable=True),
    sa.Column('numero_serie', sa.String(), nullable=True),
    sa.Column('fecha_adquisicion', sa.DateTime(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('especificaciones', sa.String(), nullable=True),
    sa.Column('foto_url', sa.String(), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('resguardo_nombre', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['laboratorio_id'], ['laboratorios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_inventario')
    )
    with op.batch_alter_table('activos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activos_id'), ['id'], unique=False)

    op.create_table('computadoras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('laboratorio_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('fila', sa.String(), nullable=True),
    sa.Column('specs', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['laboratorio_id'], ['laboratorios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('computadoras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_computadoras_id'), ['id'], unique=False)

    op.create_table('horarios_disponibles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('laboratorio_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.String(), nullable=False),
    sa.Column('hora_fin', sa.String(), nullable=False),
    sa.Column('cuatrimestre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['laboratorio_id'], ['laboratorios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('horarios_disponibles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_horarios_disponibles_id'), ['id'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('numero_empleado', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('rol', sa.Enum('SUPER_ADMIN', 'LAB_ADMIN', 'DOCENTE', 'ALUMNO', name='rolusuario'), nullable=False),
    sa.Column('laboratorio_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['laboratorio_id'], ['laboratorios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_empleado')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_id'), ['id'], unique=False)

    op.create_table('bloqueos_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horario_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['horario_id'], ['horarios_disponibles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bloqueos_slot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bloqueos_slot_id'), ['id'], unique=False)

    op.create_table('incidentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activo_id', sa.Integer(), nullable=True),
    sa.Column('computadora_id', sa.Integer(), nullable=True),
    sa.Column('laboratorio_id', sa.Integer(), nullable=True),
    sa.Column('origen', sa.String(), nullable=True),
    sa.Column('origen_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('reportado_por_id', sa.Integer(), nullable=True),
    sa.Column('fecha_reporte', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('prioridad', sa.String(), nullable=True),
    sa.Column('notas_seguimiento', sa.String(), nullable=True),
    sa.Column('fecha_resolucion', sa.DateTime(), nullable=True),
    sa.Column('costo_reparacion', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['activo_id'], ['activos.id'], ),
    sa.ForeignKeyConstraint(['computadora_id'], ['computadoras.id'], ),
    sa.ForeignKeyConstraint(['laboratorio_id'], ['laboratorios.id'], ),
    sa.ForeignKeyConstraint(['reportado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidentes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidentes_id'), ['id'], unique=False)

    op.create_table('mantenimientos_preventivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activo_id', sa.Integer(), nullable=True),
    sa.Column('computadora_id', sa.Integer(), nullable=True),
    sa.Column('laboratorio_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('periodicidad', sa.String(), nullable=True),
    sa.Column('fecha_programada', sa.DateTime(), nullable=False),
    sa.Column('fecha_limite', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_completado', sa.DateTime(), nullable=True),
    sa.Column('completado_por_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('checklist', sa.String(), nullable=True),
    sa.Column('notas_result', sa.String(), nullable=True),
    sa.Column('costo', sa.Float(), nullable=True),
    sa.Column('duracion_min', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activo_id'], ['activos.id'], ),
    sa.ForeignKeyConstraint(['completado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['computadora_id'], ['computadoras.id'], ),
    sa.ForeignKeyConstraint(['laboratorio_id'], ['laboratorios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mantenimientos_preventivos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mantenimientos_preventivos_id'), ['id'], unique=False)

    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('mensaje', sa.String(), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notificaciones_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificaciones_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('prestamos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activo_id', sa.Integer(), nullable=False),
    sa.Column('solicitante_nombre', sa.String(), nullable=False),
    sa.Column('solicitante_id_escolar', sa.String(), nullable=False),
    sa.Column('docente_responsable_id', sa.Integer(), nullable=True),
    sa.Column('autorizado_por', sa.Integer(), nullable=False),
    sa.Column('fecha_salida', sa.DateTime(), nullable=True),
    sa.Column('fecha_retorno_esperada', sa.DateTime(), nullable=False),
    sa.Column('fecha_retorno_real', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('condicion_salida', sa.String(), nullable=True),
    sa.Column('condicion_retorno', sa.String(), nullable=True),
    sa.Column('observaciones_salida', sa.String(), nullable=True),
    sa.Column('observaciones_retorno', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['activo_id'], ['activos.id'], ),
    sa.ForeignKeyConstraint(['autorizado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['docente_responsable_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prestamos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prestamos_id'), ['id'], unique=False)

    op.create_table('reservaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horario_id', sa.Integer(), nullable=False),
    sa.Column('laboratorio_id', sa.Integer(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('docente_suplente_id', sa.Integer(), nullable=True),
    sa.Column('materia', sa.String(), nullable=False),
    sa.Column('grupo', sa.String(), nullable=False),
    sa.Column('cuatrimestre', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=False),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['docente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['docente_suplente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['horario_id'], ['horarios_disponibles.id'], ),
    sa.ForeignKeyConstraint(['laboratorio_id'], ['laboratorios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservaciones_id'), ['id'], unique=False)

    op.create_table('sesiones_clase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservacion_id', sa.Integer(), nullable=True),
    sa.Column('laboratorio_id', sa.Integer(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('materia', sa.String(), nullable=False),
    sa.Column('grupo', sa.String(), nullable=False),
    sa.Column('codigo_sesion', sa.String(), nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=True),
    sa.Column('fin_estimado', sa.DateTime(), nullable=True),
    sa.Column('fin_real', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('observacion_general', sa.String(), nullable=True),
    sa.Column('overtime_min', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['docente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['laboratorio_id'], ['laboratorios.id'], ),
    sa.ForeignKeyConstraint(['reservacion_id'], ['reservaciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_sesion')
    )
    with op.batch_alter_table('sesiones_clase', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sesiones_clase_id'), ['id'], unique=False)

    op.create_table('solicitudes_conflicto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservacion_id', sa.Integer(), nullable=False),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('materia', sa.String(), nullable=False),
    sa.Column('grupo', sa.String(), nullable=False),
    sa.Column('motivo', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('resolucion_notas', sa.String(), nullable=True),
    sa.Column('resuelto_por_id', sa.Integer(), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=True),
    sa.Column('fecha_resolucion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reservacion_id'], ['reservaciones.id'], ),
    sa.ForeignKeyConstraint(['resuelto_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solicitudes_conflicto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitudes_conflicto_id'), ['id'], unique=False)

    op.create_table('asignaciones_pc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sesion_id', sa.Integer(), nullable=False),
    sa.Column('computadora_id', sa.Integer(), nullable=False),
    sa.Column('alumno_nombre', sa.String(), nullable=False),
    sa.Column('alumno_matricula', sa.String(), nullable=False),
    sa.Column('hora_asignacion', sa.DateTime(), nullable=True),
    sa.Column('hora_liberacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['computadora_id'], ['computadoras.id'], ),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones_clase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asignaciones_pc', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asignaciones_pc_id'), ['id'], unique=False)

    op.create_table('observaciones_pc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sesion_id', sa.Integer(), nullable=False),
    sa.Column('computadora_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('prioridad', sa.String(), nullable=True),
    sa.Column('atendida', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['computadora_id'], ['computadoras.id'], ),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones_clase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observaciones_pc', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observaciones_pc_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observaciones_pc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observaciones_pc_id'))

    op.drop_table('observaciones_pc')
    with op.batch_alter_table('asignaciones_pc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asignaciones_pc_id'))

    op.drop_table('asignaciones_pc')
    with op.batch_alter_table('solicitudes_conflicto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitudes_conflicto_id'))

    op.drop_table('solicitudes_conflicto')
    with op.batch_alter_table('sesiones_clase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sesiones_clase_id'))

    op.drop_table('sesiones_clase')
    with op.batch_alter_table('reservaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservaciones_id'))

    op.drop_table('reservaciones')
    with op.batch_alter_table('prestamos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prestamos_id'))

    op.drop_table('prestamos')
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificaciones_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_notificaciones_id'))

    op.drop_table('notificaciones')
    with op.batch_alter_table('mantenimientos_preventivos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mantenimientos_preventivos_id'))

    op.drop_table('mantenimientos_preventivos')
    with op.batch_alter_table('incidentes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidentes_id'))

    op.drop_table('incidentes')
    with op.batch_alter_table('bloqueos_slot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bloqueos_slot_id'))

    op.drop_table('bloqueos_slot')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('horarios_disponibles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_horarios_disponibles_id'))

    op.drop_table('horarios_disponibles')
    with op.batch_alter_table('computadoras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_computadoras_id'))

    op.drop_table('computadoras')
    with op.batch_alter_table('activos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activos_id'))

    op.drop_table('activos')
    with op.batch_alter_table('laboratorios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_laboratorios_id'))

    op.drop_table('laboratorios')
    with op.batch_alter_table('catalogo_materias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalogo_materias_id'))

    op.drop_table('catalogo_materias')
    with op.batch_alter_table('catalogo_alumnos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalogo_alumnos_matricula'))
        batch_op.drop_index(batch_op.f('ix_catalogo_alumnos_id'))

    op.drop_table('catalogo_alumnos')
    # ### end Alembic commands ###
